<?php

$this->extend('layouts/admin/default');

$label = ($this->item['id'] ? 'Редактиране' : 'Добавяне');

$this->section('title', $label);

$this->hookToMenu('main', 'control.mail.templates', $label);

?>

<h1><?php echo $label; ?></h1>

<form class="form-horizontal" action="<?php echo route(); ?>" method="post" enctype="multipart/form-data">
    <div style="margin-bottom: 20px">
        <?php echo $this->form->btnSave; ?>
        <?php echo $this->form->btnApply; ?>
        <?php echo $this->form->btnBack; ?>
    </div>
    <div class="row">
        <div class="col-md-9">
            <div class="panel panel-default">
                <div class="panel-heading">&nbsp;</div>
                <div class="panel-body">
                    <div class="form-group">
                        <div class="col-md-6">
                            <?php echo $this->form->name->renderLabel(); ?>
                            <?php echo $this->form->name; ?>
                        </div>
                        <div class="col-md-6">
                            <?php echo $this->form->alias->renderLabel(); ?>
                            <?php echo $this->form->alias; ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-12">
                            <?php echo $this->form->description->renderLabel(); ?>
                            <?php echo $this->form->description; ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="panel panel-default">
                <div class="panel-heading">&nbsp;</div>
                <div class="panel-body">
                    <div class="form-group" style="margin-bottom: 0;">
                        <div class="col-md-12">
                            <?php echo $this->form->active; ?>
                            <?php echo $this->form->active->getLabel(); ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div>
        <?php echo $this->form->btnSave; ?>
        <?php echo $this->form->btnApply; ?>
        <?php echo $this->form->btnBack; ?>
    </div>
</form>