<?php

$label = 'Email шаблони';

$this->extend('layouts/admin/default');

$this->section('title', $label);

?>

<h1><?php echo $label; ?></h1>

<div class="row">
    <div class="col-md-9 table-responsive">
        <?php echo $this->grid; ?>
    </div>
    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">Филтри</div>
            <div class="panel-body">
                <form action="<?php echo route(); ?>" method="post">
                    <div class="form-group">
                        <label class="control-label">Име</label>
                        <input class="form-control" type="text" name="filters[name]" value="<?php echo (isset($this->filters['name']) ? $this->filters['name'] : ''); ?>" />
                    </div>
                    <div class="form-group">
                        <label class="control-label">Псевдоним</label>
                        <input class="form-control" type="text" name="filters[alias]" value="<?php echo (isset($this->filters['alias']) ? $this->filters['alias'] : ''); ?>" />
                    </div>
                    <div class="form-group">
                        <label class="control-label">Описание</label>
                        <input class="form-control" type="text" name="filters[description]" value="<?php echo (isset($this->filters['description']) ? $this->filters['description'] : ''); ?>" />
                    </div>
                    <div class="form-group">
                        <input class="btn btn-primary" type="submit" name="filters[filter]" value="Филтриране" />
                        <input class="btn btn-default" type="submit" name="filters[reset]" value="Нулиране" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>